// Researched condo & townhome buildings per neighbourhood, keyed by
// neighbourhood slug. Rendered as the "Condo buildings" section on each
// public neighbourhood page. Buildings that also have a dedicated condo
// page (condo_buildings table) are matched by name at the API layer and
// linked; entries here are display-only names (+ optional address).
//
// Sourced July 2026 from MLS-backed condo directories (calgary-real-estate.com,
// teamhripko.ca, bestcalgaryhomes.com, calgarycitycondos.com, builder sites)
// and cross-checked across sources. Only buildings named in at least one
// source are included — estate neighbourhoods with no named complexes are
// simply absent. Rental-only buildings were excluded where identifiable.
//
// Seeding is fill-if-empty: seed.ts copies a neighbourhood's list into the
// condo_buildings_list column only when that column is still '[]', so
// admin edits are never clobbered on redeploy.

export interface NeighbourhoodCondoBuilding {
  name: string;
  address?: string;
}

export const NEIGHBOURHOOD_CONDO_BUILDINGS: Record<
  string,
  NeighbourhoodCondoBuilding[]
> = {
  "eau-claire": [
    { name: "Eau Claire Estates", address: "500 Eau Claire Avenue SW" },
    { name: "The Concord", address: "738 1 Avenue SW" },
    { name: "Princeton Cityscape", address: "660 Eau Claire Avenue SW" },
    { name: "Princeton Grand", address: "600 Princeton Way SW" },
    { name: "Princeton Hall", address: "690 Princeton Way SW" },
    { name: "Princeton Waterfront", address: "670 & 680 Princeton Way SW" },
    { name: "Liberte", address: "804 3 Avenue SW" },
    { name: "Point on the Bow", address: "837 2 Avenue SW" },
    { name: "First & Park", address: "730 2 Avenue SW" },
    { name: "Prince's Island Estates", address: "400 Eau Claire Avenue SW" },
    { name: "Prince's Crossing", address: "738 3 Avenue SW" },
    { name: "Chateau La Caille", address: "200 La Caille Place SW" },
    { name: "La Caille Parke Place", address: "110 7 Street SW" },
    { name: "Eau Claire Lookout", address: "801 2 Avenue SW" },
    { name: "Pavilions of Eau Claire", address: "777 3 Avenue SW" },
    { name: "Churchill Estates", address: "701 3 Avenue SW" },
    { name: "Waterfront", address: "222 Riverfront Avenue SW" },
    { name: "Outlook at Waterfront", address: "128 2 Street SW" },
    { name: "Parkside at Waterfront", address: "108 Waterfront Court SW" },
    { name: "205 Riverfront", address: "205 Riverfront Avenue SW" },
    { name: "River Run" },
    { name: "Sonoma Place" },
  ],
  "beltline": [
    { name: "6th and Tenth", address: "1010 6 Street SW" },
    { name: "Alura", address: "1320 1 Street SE" },
    { name: "Arriva", address: "433 11 Avenue SE" },
    { name: "Astoria on Tenth" },
    { name: "Calla", address: "626 14 Avenue SW" },
    { name: "Castello", address: "530 12 Avenue SW" },
    { name: "Chocolate", address: "188 15 Avenue SW" },
    { name: "Colours", address: "135 13 Avenue SW" },
    { name: "The Cozart", address: "1001 14 Avenue SW" },
    { name: "Darlington Arms", address: "317 14 Avenue SW" },
    { name: "Dorchester Square", address: "924 14 Avenue SW" },
    { name: "Drake", address: "1500 7 Street SW" },
    { name: "EightWelve", address: "812 14 Avenue SW" },
    { name: "Emerald Stone", address: "836 15 Avenue SW" },
    { name: "The Estate", address: "720 13 Avenue SW" },
    { name: "Fontainebleau Estates", address: "215 14 Avenue SW" },
    { name: "The Guardian North Tower", address: "1122 3 Street SE" },
    { name: "The Guardian South Tower", address: "1188 3 Street SE" },
    { name: "Harcourt Estates", address: "1334 14 Avenue SW" },
    { name: "Hudson Lofts", address: "535 10 Avenue SW" },
    { name: "The Huntsman", address: "1334 13 Avenue SW" },
    { name: "Imperial Lofts", address: "220 11 Avenue SE" },
    { name: "Keynote One", address: "220 12 Avenue SE" },
    { name: "Keynote Two", address: "225 11 Avenue SE" },
    { name: "Lewis Lofts", address: "240 11 Avenue SW" },
    { name: "Lincoln", address: "313 11 Avenue SW" },
    { name: "The Lucida" },
    { name: "Luna", address: "1111 10 Street SW" },
    { name: "Manhattan Lofts", address: "1117 1 Street SW" },
    { name: "Mark on 10th", address: "901 10 Avenue SW" },
    { name: "The Montana", address: "817 15 Avenue SW" },
    { name: "Nova", address: "1118 12 Avenue SW" },
    { name: "Nude by Battistella", address: "1319 14 Avenue SW" },
    { name: "Nuera", address: "211 13 Avenue SE" },
    { name: "Park Place", address: "323 13 Avenue SE" },
    { name: "Park Point", address: "310 12 Avenue SW" },
    { name: "The Park", address: "303 13 Avenue SW" },
    { name: "Polo Terrace", address: "126 14 Avenue SW" },
    { name: "Residences of Mount Royal", address: "881 15 Avenue SW" },
    { name: "The Ravenwood" },
    { name: "The Royal", address: "930 16 Avenue SW" },
    { name: "The Royal Oak" },
    { name: "The Sandpiper" },
    { name: "Sasso", address: "1410 1 Street SE" },
    { name: "The Savoy", address: "923 15 Avenue SW" },
    { name: "Smith", address: "1501 6 Street SW" },
    { name: "Stella", address: "1110 11 Street SW" },
    { name: "Union Square", address: "215 13 Avenue SW" },
    { name: "Vantage Pointe", address: "1053 10 Street SW" },
    { name: "Vetro", address: "210 15 Avenue SE" },
    { name: "Villa Royale", address: "620 15 Avenue SW" },
    { name: "Wellington Estates", address: "1330 15 Avenue SW" },
    { name: "Westbow", address: "1304 15 Avenue SW" },
    { name: "Xenex on 12th", address: "788 12 Avenue SW" },
  ],
  "mission": [
    { name: "Duke at Mission", address: "110 18 Avenue SW" },
    { name: "The District", address: "305 18 Avenue SW" },
    { name: "Soho", address: "323 18 Avenue SW" },
    { name: "The Legacy", address: "138 18 Avenue SE" },
    { name: "Taymar", address: "317 19 Avenue SW" },
    { name: "Tribeca", address: "323 20 Avenue SW" },
    { name: "LeBeau", address: "328 21 Avenue SW" },
    { name: "Mission Crossing", address: "540 21 Avenue SW" },
    { name: "Tela", address: "317 22 Avenue SW" },
    { name: "Destiny", address: "333 22 Avenue SW" },
    { name: "Elements of Mission", address: "208 Holy Cross Lane SW" },
    { name: "La Rive", address: "108 25 Avenue SW" },
    { name: "Hampton Court", address: "133 25 Avenue SW" },
    { name: "Riverscape", address: "225 25 Avenue SW" },
    { name: "Grandview", address: "228 26 Avenue SW" },
    { name: "River's Edge", address: "220 26 Avenue SW" },
    { name: "Riverstone", address: "318 26 Avenue SW" },
    { name: "Roxboro House", address: "330 26 Avenue SW" },
    { name: "The River" },
    { name: "Xolo" },
    { name: "Athlone" },
    { name: "Elbow River Arms" },
    { name: "Lindsay Park Place" },
    { name: "Maison Neuve" },
    { name: "Mission Bridge Estates" },
    { name: "Mission Court" },
    { name: "Mission Mews" },
    { name: "Mission Place" },
    { name: "Mission Royale" },
    { name: "The Regency" },
    { name: "Riverview Place" },
    { name: "The Corona" },
    { name: "The Hamilton" },
    { name: "The Vineyards" },
    { name: "Venezia Estates" },
  ],
  "lower-mount-royal": [
    { name: "Anderson Apartments", address: "804 18 Avenue SW" },
    { name: "Mantra", address: "910 18 Avenue SW" },
    { name: "Mount Royal Grande", address: "838 18 Avenue SW" },
    { name: "Ten Mount Royal", address: "1720 10 Street SW" },
    { name: "The Greystones", address: "1818 14 Street SW" },
    { name: "The Tweed", address: "1730 5A Street SW" },
    { name: "Uno", address: "836 Royal Avenue SW" },
    { name: "Brompton Court" },
    { name: "Cameron Court" },
    { name: "Cameron Mansion" },
    { name: "Carriage Villas" },
    { name: "Chateau House" },
    { name: "Chelsea Terrace" },
    { name: "Hillandale" },
    { name: "Luxxen Maisonette" },
    { name: "Modella" },
    { name: "Mount Royal Courts" },
    { name: "Mount Royal Terrace" },
    { name: "Onyx" },
    { name: "Sunward Estates" },
    { name: "The Beringer" },
    { name: "The Hallmark" },
    { name: "The Serenity" },
    { name: "York House" },
  ],
  "sunnyside": [
    { name: "The Annex", address: "327 9A Street NW" },
    { name: "The Pixel", address: "235 9A Street NW" },
    { name: "Royal Kensington", address: "630 10 Street NW" },
    { name: "Lido by Battistella", address: "1087 2 Avenue NW" },
    { name: "Ven", address: "823 5 Avenue NW" },
    { name: "City Manor" },
    { name: "Glenwood Manor" },
    { name: "Memorial Court" },
    { name: "Riley Park Estates" },
    { name: "Rondo" },
    { name: "Sierra Riverside" },
    { name: "Sunnyside Court" },
    { name: "Sunnyside Point" },
    { name: "Sunnyside Rose" },
    { name: "The Arbours" },
    { name: "Village Manor" },
  ],
  "hillhurst": [
    { name: "Ezra on Riley Park", address: "1234 5 Avenue NW" },
    { name: "The Kenten", address: "100 10A Street NW" },
    { name: "The Theodore", address: "1107 Gladstone Road NW" },
    { name: "Kensington by Bucci", address: "301 10 Street NW" },
    { name: "Kensington Mews I", address: "2 14 Street NW" },
    { name: "Kensington Mews II", address: "4 14 Street NW" },
    { name: "Kensington on the Park", address: "1110 5 Avenue NW" },
    { name: "The Vue", address: "429 14 Street NW" },
    { name: "Villagio Kensington", address: "1407 Kensington Close NW" },
    { name: "Plaza 14" },
    { name: "Providence at Kensington" },
    { name: "St. John's on Tenth" },
    { name: "Hillhurst Villa" },
    { name: "Kensington Court" },
    { name: "Kensington Park Plaza" },
    { name: "Orchard Court" },
    { name: "Providence Park" },
  ],
  "west-hillhurst": [
    { name: "Frontier", address: "110 18A Street NW" },
    { name: "Savoy", address: "119 19 Street NW" },
    { name: "Kensington Estates" },
    { name: "Parkwood Towers" },
    { name: "Riverview Estates" },
    { name: "The Manors" },
    { name: "The Rimrock" },
    { name: "The Timberstone" },
    { name: "Westminster Gardens" },
  ],
  "bridgeland-riverside": [
    { name: "Radius" },
    { name: "Bridgeland Crossings" },
    { name: "Bridgeland Crossings II" },
    { name: "Era by Minto" },
    { name: "Next" },
    { name: "LiFTT" },
    { name: "43 Park", address: "811 5 Street NE" },
    { name: "Bridgeland Hill" },
    { name: "Pontefino" },
    { name: "Pontefino II" },
    { name: "McPherson Place" },
    { name: "Steps Bridgeland" },
    { name: "Acqua" },
    { name: "Avalon Court" },
    { name: "Bella Citta" },
    { name: "Bella Lusso" },
    { name: "Bridgeland Heights" },
    { name: "Bridgeview Park Place" },
    { name: "Cobblestone Court" },
    { name: "Eagle Terrace" },
    { name: "Hanford House" },
    { name: "High Pointe" },
    { name: "Jubilee Manor" },
    { name: "McDougall Court" },
    { name: "Mi Casa" },
    { name: "Olive" },
    { name: "Portico" },
    { name: "Riverhill Gardens" },
    { name: "Riverton Place" },
    { name: "Suntree Villas" },
    { name: "The Waterford of Bridgeland" },
  ],
  "inglewood": [
    { name: "Avli on Atlantic", address: "1020 9 Avenue SE" },
    { name: "SoBow", address: "63 Inglewood Park SE" },
    { name: "Inglewood Grove" },
    { name: "Inglewood Place" },
    { name: "Pearce Gardens" },
    { name: "Aviara Place" },
    { name: "Inglewood Corners" },
    { name: "Inglewood on Bow" },
    { name: "Inglewood Village" },
    { name: "McGill Apartments" },
  ],
  "altadore": [
    { name: "Treo @ Marda Loop", address: "3410 20 Street SW" },
    { name: "Marda Station", address: "2212 34 Avenue SW" },
    { name: "Dream", address: "2420 34 Avenue SW" },
    { name: "Kabo", address: "3600 15A Street SW" },
    { name: "Gateway Marda Loop" },
    { name: "Spirit of Marda Loop" },
    { name: "Spirit of Marda Loop 2" },
    { name: "Equinox" },
    { name: "The Montecito" },
    { name: "Galleries of Marda Loop" },
    { name: "Marin Harbour Town Homes" },
    { name: "Copa" },
    { name: "Skywood Estates" },
    { name: "Riverpark Manor" },
    { name: "Riverpark Townhomes" },
    { name: "Altadena Terrace" },
    { name: "Altador Mews" },
    { name: "Altadore Concept" },
    { name: "West" },
    { name: "Marlo", address: "1716 36 Avenue SW" },
  ],
  "garrison-woods": [
    { name: "Courtyards of Garrison Woods", address: "3000 Marda Link SW" },
    { name: "Gateway Garrison Woods", address: "2233 34 Avenue SW" },
    { name: "Garrison Square" },
    { name: "Brighton Court" },
    { name: "Sanctuary Woods" },
    { name: "The Brownstones" },
    { name: "Altadore Court" },
    { name: "Versailles" },
  ],
  "currie-barracks": [
    { name: "Overture in Currie Barracks", address: "23 Burma Star Road SW" },
    { name: "Axess", address: "95 Burma Star Road SW" },
    { name: "The Armory" },
    { name: "Queensway at Currie" },
    { name: "Quesnay at Currie" },
    { name: "Contempo" },
  ],
  "south-calgary": [
    { name: "Avenue 33", address: "3450 19 Street SW" },
    { name: "VIBE14", address: "1510 30 Avenue SW" },
    { name: "GLAS", address: "1808 27 Avenue SW" },
    { name: "Coco by Sarina", address: "3375 15 Street SW" },
    { name: "The Delano" },
    { name: "The Cerulean" },
    { name: "The 14th Street Lofts" },
    { name: "The Meritage" },
    { name: "Aurora Gardens" },
    { name: "Aurora Place" },
    { name: "Aurora Townhouse" },
    { name: "Citadel House" },
    { name: "Leaton Place" },
    { name: "Marda Court" },
    { name: "Redwood Manor" },
    { name: "Sara Lee Villa" },
    { name: "Sara Lee Manor" },
    { name: "Valhalla" },
    { name: "Vive" },
    { name: "Vantaa" },
    { name: "Windermere Place" },
  ],
  "richmond": [
    { name: "The Casel", address: "2505 17 Avenue SW" },
  ],
  "bankview": [
    { name: "Bankview Gate" },
    { name: "Noran House" },
    { name: "Sonata" },
    { name: "Valhalla View" },
    { name: "Pavilions" },
    { name: "Hardwood View" },
    { name: "City View Terrace" },
    { name: "City View Apartments" },
    { name: "City View Lofts" },
    { name: "The Manhattan" },
    { name: "Allentree Apartments" },
    { name: "Chelsea Lofts" },
    { name: "Providence at Bankview" },
    { name: "Victorian Courts" },
    { name: "Bankpark Place" },
    { name: "Tiboron Court" },
    { name: "Casa Loma" },
    { name: "Cedar View" },
    { name: "Bankview Villas" },
    { name: "Bella Vista" },
    { name: "Bridges" },
    { name: "Green Brier on the Park" },
    { name: "Knob Hill Estates" },
    { name: "Parkridge Manor" },
    { name: "Regal Terrace West" },
    { name: "Ridgewood Condos" },
    { name: "Riverglen Park" },
    { name: "Sierra Vista" },
    { name: "Flat17" },
    { name: "Stoneset" },
  ],
  "upper-mount-royal": [
    { name: "Palace Royale", address: "629 Royal Avenue SW" },
  ],
  "mount-pleasant": [
    { name: "The Neville", address: "1022 16 Avenue NW" },
    { name: "Summerfields" },
    { name: "Mount Pleasant Court" },
    { name: "Birchcrest" },
  ],
  "parkdale": [
    { name: "Riviera on the Bow", address: "3320 3 Avenue NW" },
    { name: "The Riverton at Parkdale", address: "540 34 Street NW" },
    { name: "Hemisphere on Bow" },
    { name: "Urban View by the River" },
    { name: "Parkdale Point" },
    { name: "River Park West" },
    { name: "Park Haven Place" },
    { name: "Park Haven Villas" },
    { name: "The Henry in Parkdale" },
  ],
  "britannia": [
    { name: "Britanna Park Manor", address: "4915 8 Street SW" },
  ],
  "rideau-park": [
    { name: "Rideau Towers", address: "Rideau Place SW" },
    { name: "Renfrew House", address: "3204 Rideau Place SW" },
    { name: "Cumberland House", address: "3232 Rideau Place SW" },
    { name: "Rutland House", address: "3316 Rideau Place SW" },
    { name: "Devonshire House", address: "3339 Rideau Place SW" },
  ],
  "eagle-ridge": [
    { name: "Covenant House", address: "222 Eagle Ridge Drive SW" },
  ],
  "parkhill": [
    { name: "The Courtyard", address: "3912 Stanley Road SW" },
    { name: "Erlton Terrace" },
    { name: "Parkhill Vistas" },
    { name: "Parkview Terrace" },
    { name: "Old Parkhill School" },
    { name: "Parkhill Flats", address: "4120 1A Street SW" },
  ],
  "hounsfield-heights-briar-hill": [
    { name: "The Renaissance", address: "1718 & 1726 14 Avenue NW" },
    { name: "Cedar Brae Gardens", address: "1620 8 Avenue NW" },
  ],
  "windsor-park": [
    { name: "Arlington Place" },
    { name: "Britannia Terrace" },
    { name: "Chateau Lucille" },
    { name: "Chinook Manor" },
    { name: "Chinook West" },
    { name: "Chinook Winds Manor" },
    { name: "Country Club Estates" },
    { name: "Oxford Parc" },
    { name: "Southglen" },
    { name: "The Windsor" },
    { name: "The Windsors" },
    { name: "Windsor Manor" },
    { name: "Windsor Mews" },
    { name: "Windsor Park Court" },
    { name: "Windsor Park Green" },
    { name: "Windsor Point" },
    { name: "York House" },
    { name: "York Place" },
  ],
  "elboya": [
    { name: "The Stanley", address: "4704 Stanley Road SW" },
  ],
  "aspen-woods": [
    { name: "Valmont at Aspen Stone", address: "Aspenmont Heights SW" },
    { name: "Gallant Ridge", address: "211 Aspen Stone Boulevard SW" },
    { name: "The Enclave at Castle Keep", address: "Ascot Circle SW" },
    { name: "Mosaic of Aspen Hills" },
    { name: "Zen in Aspen" },
    { name: "Seventeen Hundred at Aspen Estates", address: "1700 73 Street SW" },
  ],
  "springbank-hill": [
    { name: "85th & Park", address: "8355 19 Avenue SW" },
    { name: "The Whitney", address: "2117 81 Street SW" },
    { name: "Robson Summit of Montreux", address: "Val Gardena View SW" },
    { name: "West 69th", address: "69 Springborough Court SW" },
    { name: "Mountain View Terrace" },
    { name: "College Gate" },
    { name: "Springbank Villas" },
    { name: "Elkwood Townhomes at Aspen Spring" },
    { name: "Juniper Townhomes", address: "2231 81 Street SW" },
    { name: "Aurora at Aspen Spring" },
    { name: "Timberline Estates" },
  ],
  "patterson": [
    { name: "The Mansions at Prominence Point" },
    { name: "The Brickburn" },
    { name: "The Terraces of Broadcast Hill" },
    { name: "Patterson Bluffs", address: "Patterson View SW" },
    { name: "Hillside Terraces at Patterson Bluffs", address: "Patterson View SW" },
    { name: "Patterson Lofts" },
    { name: "Patina Park" },
    { name: "Capilano Gardens" },
    { name: "Capilano Heights" },
    { name: "Capilano Point" },
    { name: "Capilano Ridge" },
    { name: "La Mesa" },
    { name: "Indian Bluff" },
    { name: "Patterson Ridge Estates" },
    { name: "Legacy Estates - Patterson Heights" },
    { name: "Prominence Park" },
    { name: "Prominence Heights" },
  ],
  "discovery-ridge": [
    { name: "The Wedgewoods", address: "30 Discovery Ridge Close SW" },
    { name: "Wedgewoods of New Discovery", address: "20 Discovery Ridge Close SW" },
    { name: "Discovery Heights", address: "Discovery Heights SW" },
    { name: "Discovery Wood Villas", address: "Discovery Woods Villa SW" },
  ],
  "west-springs": [
    { name: "Gateway by Truman", address: "8505 Broadcast Avenue SW" },
    { name: "Gateway East", address: "8445 Broadcast Avenue SW" },
    { name: "The Mondrian", address: "8370 Broadcast Avenue SW" },
    { name: "Plaza at West District", address: "8375 Broadcast Avenue SW" },
    { name: "Vivace", address: "8530 8A Avenue SW" },
    { name: "Parkside at West District", address: "835 78 Street SW" },
    { name: "Wentworth Pointe", address: "805 85 Street SW" },
    { name: "Wentworth", address: "8000 Wentworth Drive SW" },
    { name: "The Summit at Wentworth South", address: "60 Welcome Place SW" },
    { name: "Sanctuary" },
    { name: "Springside Villas" },
  ],
  "lakeview": [
    { name: "Lakeview Green 1", address: "3130 66 Avenue SW" },
    { name: "Lakeview Green 2", address: "3131 66 Avenue SW" },
    { name: "Lakeview Green 3", address: "3240 66 Avenue SW" },
  ],
  "signal-hill": [
    { name: "Sienna Park Green Village", address: "Sienna Park Green SW" },
    { name: "Sierra's West I", address: "6868 Sierra Morena Boulevard SW" },
    { name: "Sierra's West II" },
    { name: "Dana Village", address: "1818 Simcoe Boulevard SW" },
    { name: "Sierras of Richmond Hill", address: "7239 Sierra Morena Boulevard SW" },
    { name: "The Pavilions of Richmond Hill", address: "10, 20 & 30 Sierra Morena Mews SW" },
    { name: "The Tudors", address: "60 Sierra Morena Landing SW" },
    { name: "The Landings", address: "Sierra Morena Landing SW" },
    { name: "Signal Hill Estates", address: "100 Signature Way SW" },
    { name: "Signal Hill Green" },
    { name: "Signal Hill Villas" },
    { name: "Stonehurst" },
    { name: "Manor Villas" },
    { name: "Cactus Ridge" },
    { name: "Georgian Bay Manors" },
    { name: "Statesman Villas" },
    { name: "The Vista at Richmond Hill" },
    { name: "The Homesteads" },
  ],
  "bayview": [
    { name: "Bay Point", address: "Baycrest Place SW" },
  ],
  "kelvin-grove": [
    { name: "Kelvin Grove Condominiums", address: "6919 Elbow Drive SW" },
    { name: "Kelvin Court", address: "910 70 Avenue SW" },
  ],
  "oakridge": [
    { name: "Oakridge Gardens" },
    { name: "Oakwood Lane" },
    { name: "Oakridge Village" },
    { name: "Heritage Manor", address: "9500 Oakfield Drive SW" },
  ],
  "woodbine": [
    { name: "Woodacres" },
    { name: "Woodmount Terrace" },
    { name: "The Woodsman" },
    { name: "Tiffany Lane" },
    { name: "Woodborough Terrace" },
  ],
  "canyon-meadows": [
    { name: "Canyon Pines Condominiums" },
    { name: "The Meadows" },
    { name: "Fish Creek Villas" },
    { name: "Holly Meadows" },
    { name: "Canyon Creek Heights" },
    { name: "Canyon Glen Townhouses" },
    { name: "Canterbury Gardens" },
    { name: "Anderson Place" },
  ],
  "willow-park": [
    { name: "Hearthstone Place", address: "10910 & 10940 Bonaventure Drive SE" },
    { name: "Willow Tree Village" },
    { name: "Willow Court Green" },
    { name: "Willow Glen" },
    { name: "Woodlands Place" },
  ],
  "lake-bonavista": [
    { name: "Gateway Southcentre", address: "11811 Lake Fraser Drive SE" },
    { name: "Bonavista Estates" },
    { name: "Bonavista Estates II", address: "1311 Lake Fraser Green SE" },
    { name: "Chateaux Bonavista" },
  ],
  "chaparral": [
    { name: "Chaparral Pointe", address: "428 Chaparral Ravine View SE" },
    { name: "Riverside Townhomes" },
    { name: "Chaparral Estates" },
    { name: "Chaparral Village" },
  ],
  "alpine-park": [
    { name: "Woodland at Alpine Park" },
  ],
  "pine-creek": [
    { name: "Pine Creek Towns by Truman", address: "395 210 Avenue SW" },
    { name: "The Villas at Sirocco" },
  ],
  "mahogany": [
    { name: "Reflection at Westman Village" },
    { name: "Odyssey at Westman Village" },
    { name: "Calligraphy at Westman Village" },
    { name: "The Journey Club at Westman Village" },
    { name: "Sandgate" },
    { name: "Zen Mahogany", address: "135 Mahogany Parade SE" },
    { name: "Waterside at Mahogany" },
  ],
  "auburn-bay": [
    { name: "Canoe" },
    { name: "Regatta" },
    { name: "Stonecroft Auburn Bay" },
    { name: "Auburn Walk", address: "105 Auburn Meadows Drive SE" },
    { name: "Auburn Rise", address: "100 Auburn Meadows Common SE" },
    { name: "Zen in Auburn Bay" },
  ],
  "cranston": [
    { name: "Cranston Ridge" },
    { name: "Mosaic Cranston", address: "71 Cranarch Road SE" },
    { name: "Mosaic Riverstone" },
    { name: "Zen Riverstone", address: "Cranbrook Square SE" },
    { name: "Villas of Riverstone", address: "Cranston Avenue SE" },
    { name: "Riverstone Manor" },
  ],
  "edgemont": [
    { name: "Edgecliffe Estates" },
    { name: "Hillsboro" },
    { name: "Edgepark Villas" },
    { name: "Dreamview Village" },
    { name: "Edgedale Gardens" },
    { name: "Summit Point" },
    { name: "Summit Point Estates" },
    { name: "Edgemont Villas" },
    { name: "Chimney Hill" },
    { name: "Edgevalley View Estates" },
  ],
  "hamptons": [
    { name: "La Vita" },
    { name: "La Vita Pointe" },
    { name: "Chateaux One" },
    { name: "Chateaux on Eighteen" },
    { name: "Hamptons Rise Estate Villas" },
    { name: "Hamptons Park Estate Villas" },
    { name: "Hamptons Way Villas" },
    { name: "Hamptons Bay Villas" },
  ],
  "varsity-estates": [
    { name: "The Groves of Varsity", address: "16, 24 & 32 Varsity Estates Circle NW" },
    { name: "Chateau on the Green", address: "1815 Varsity Estates Drive NW" },
    { name: "Varsity Estates Village" },
  ],
  "evanston": [
    { name: "Evanston Square", address: "2300 Evanston Square NW" },
    { name: "Arrive at Evanston" },
  ],
  "elbow-valley": [
    { name: "Swift Creek Villas", address: "Clear Creek Place" },
    { name: "Riverside Villas", address: "Elbow Ridge Haven" },
    { name: "Hidden Hollow Villas", address: "Lott Creek Hollow" },
    { name: "Bent Tree Place Villas" },
    { name: "Whispering Woods Terrace Villas" },
    { name: "Whispering Water Way Villas" },
    { name: "Clearwater Way Villas" },
    { name: "Alpine Meadow Villas" },
    { name: "Lott Creek Green & Lott Creek View Villas" },
  ],
  "harmony": [
    { name: "Harmony Lakefront by StreetSide" },
    { name: "Harmony Village Towns by StreetSide" },
    { name: "Harmony Heath by StreetSide" },
  ],
  "watermark": [
    { name: "The Villas at Watermark" },
  ],
  "bearspaw": [
    { name: "Bearspaw Manor Estates", address: "Country Club Lane" },
  ],
  "heritage-pointe": [
    { name: "The Villas of Artesia", address: "Artesia Gate, Heritage Pointe" },
  ],
  "coopers-crossing": [
    { name: "Acadia Villas at Cooper's Crossing" },
    { name: "Cooper's Gardens" },
    { name: "Elevate at Cooper's Crossing" },
  ],
  "bayside": [
    { name: "The Breeze", address: "2370 Bayside Road SW, Airdrie" },
  ],
  "spring-creek": [
    { name: "Tamarack Lodge" },
    { name: "Jack Pine Lodge" },
    { name: "White Spruce Lodge", address: "905 Spring Creek Drive, Canmore" },
    { name: "Creekstone Mountain Lodge", address: "707 Spring Creek Drive, Canmore" },
    { name: "Moraine Ridge Lodge", address: "600 Spring Creek Drive, Canmore" },
    { name: "Glacier Rock Lodge", address: "505 Spring Creek Drive, Canmore" },
    { name: "Rundle Cliffs Lodge", address: "379 Spring Creek Drive, Canmore" },
    { name: "The Arnica Lodge", address: "1300 Spring Creek Drive, Canmore" },
    { name: "Grey Wolf Lodge" },
    { name: "Mountain Lynx Lodge & Chalets" },
    { name: "Black Swift Lodge" },
    { name: "Timberstone Mountain Lodge" },
    { name: "Creekside Villas" },
    { name: "Tamarack Streamside Villas", address: "Streamside Lane, Canmore" },
  ],
  "chestermere": [
    { name: "Chestermere Station", address: "300 Marina Drive, Chestermere" },
  ],
};
